version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SECRET_KEY=<secret-key>
      - MONGODB_URI=mongodb://root:password@db:27017
      - MONGODB_DB=shortener
      - JWT_EXPIRATION_TIME=86400000
      - DOMAIN_URL=http://localhost:8080
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
